travis:
  secure:
    BINSTAR_TOKEN: ckpkMExEHgWp+S9VDnwJL0EEnjpetrQqeQeNTXlI+nR6N2NoZTDRtKvQEMn+Kj9QaIZPde6LKLnuoMUH8mI06LgroCzKAKRjdEeVkUkgYAYnWxERCC6wc/LdQh5crcbljJzktC8C2gQ8QQ//VTeO+qzMmJo3EmKA6v2q116uitdEtLfv0unCKstrFSLfuAwehoeygMgXHRoYQ2ZUDIdF0Pa95ORm3T38+a2Otu8JVkbyNXcaWv1kD9z+4X+bAT3/KCEeGtTWbuOT0VggTT7loC2GoqktMX3NJLjpR5W5WKhGM9T2LQO8pN7fojatV6q1MyeVVK6fjH7UJUIz3uet15vDF8bFiHuFmgu0RgM4ivYykoZFfCqLiTgUbtKE8FlwaWDi2IT59pGKs8ag2xNwfvYSxyEBtda5FYYzCygmGZuuPB30bDzxNTP9VtMor1Tl/ibDibPqXecdAEXaCYxgNfwMF46A9UEzvI2phi543AkUgY2bZQi5FmyjK8TcWkn51SQG/441lrKGhZquUP+aUQf83y85hHo1TjBUBGTVyDSE/ywD7kTrisGUGRRxpOlTeOWQpviH7+MgCYpCnN9OZULaMkAonx6ptzT/uaPuwbuhEPhZJBXOMDWo+KM5Pol+caKYBh33B8UFQUHNmEqAtv5/sfnCaP7el5rIWyRie/k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
